- name: Run backend app
  docker_container:
    name: backend
    image: bouc402/tp-devops-backend:latest
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    state: started
    recreate: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
