- name: Run httpd proxy
  docker_container:
    name: httpd
    image: bouc402/tp-devops-httpd:latest
    networks:
      - name: app-network
    ports:
      - "80:80"
    state: started
    recreate: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
