name: CI devops 2025
on:
  push:
    branches: 
        - main
        - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        working-directory: ./backend
        run: mvn clean verify

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin



  build-and-push-backend:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}


  build-and-push-database:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

  build-and-push-httpd:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: SonarCloud Analysis
        working-directory: ./backend
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=tanyaatibouche_Devops_GHA -Dsonar.organization=tanyaatibouche -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}